// frontend/src/app/header/feature/nav-bar/static-nav-bar/static-nav-bar.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { NavbarService } from '../nav-bar.service';
import { AuthService } from '@auth0/auth0-angular';

@Component({
  selector: 'app-static-nav-bar',
  templateUrl: './static-nav-bar.component.html',
  styleUrls: ['./static-nav-bar.component.scss']
})
export class StaticNavBarComponent {
  isAuthenticated = this.authService.isAuthenticated$;
  user = this.authService.user$;

  constructor(private navbarService: NavbarService, private authService: AuthService) {}

  setNavbarToggle() {
    this.navbarService.setNavbarToggle();
  }

}

<div class='container flex justify-between items-center mx-auto gap-4'>
    <button class='text-3xl px-1' (click)="setNavbarToggle()"><fa-icon [icon]="['fas', 'bars']" /></button>
    <a routerLink="/">
        <div class='flex gap-2 items-center flex-1'>
            <img src="assets/logo.png" alt="deal fortress logo" class="logo-s"/>
            <p class='text-xl medieval-font drop-shadow-md'>DealFortress</p>
        </div>
    </a>
    <div class="flex gap-4 items-center flex-1 justify-end">
        <ng-container *ngIf="isAuthenticated | async">
            <app-auth-logout-button></app-auth-logout-button>
            <a class='text-3xl' to="/profile"><img [src]="(user | async)?.picture" alt="avatar" class='avatar rounded-full w-10' /></a> 
        </ng-container>
        <ng-container *ngIf="!(isAuthenticated | async)">
            <app-auth-login-button></app-auth-login-button>
        </ng-container>
    </div>
</div>

// frontend/src/component/Navbar/StaticNavbar.tsx
import { faBars } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { Link } from 'react-router-dom'
import logo from '../../assets/logo.png'
import { useAuth0 } from '@auth0/auth0-react'

type Props = {
    navbarToggle: boolean
    setNavbarToggle: React.Dispatch<React.SetStateAction<boolean>>
}

export const StaticNavbar = ( { setNavbarToggle, navbarToggle} : Props) => {
    
    const { loginWithRedirect, logout, isAuthenticated, user } = useAuth0();

    const authenticationBlock = () => {

      return isAuthenticated ?
      <>
        <button onClick={() => logout({logoutParams: {returnTo: window.location.origin}})}>Logout</button>
        <Link className='text-3xl' to="/profile"><img src={user?.picture} alt="avatar" className='avatar rounded-full w-10' /></Link> 
      </> 
      :
      <button onClick={() => loginWithRedirect()}>Login</button>
    }


  return (
    <div className='container flex justify-between items-center mx-auto gap-4'>
        <button className='text-3xl px-1' onClick={() => setNavbarToggle(!navbarToggle)}><FontAwesomeIcon icon={faBars} /></button>
        <Link to="/">
            <div className='flex gap-2 items-center flex-1'>
                <img src={logo} alt="deal fortress logo" className="logo-s "/>
                <p className='text-xl medieval-font drop-shadow-md'>DealFortress</p>
            </div>
        </Link>
        <div className="flex gap-4 items-center flex-1 justify-end">
            {authenticationBlock()}
        </div>
    </div>
  )
}
