// frontend/src/app/header/feature/nav-bar/nav-bar.component.ts
import { Component, OnInit } from '@angular/core';
import { NavbarService } from './nav-bar.service';

@Component({
  selector: 'app-nav-bar',
  templateUrl: './nav-bar.component.html',
  styleUrls: ['./nav-bar.component.scss']
})
export class NavBarComponent{
  navbarToggle$ = this.navbarService.navbarToggle$;
  
  constructor(private navbarService: NavbarService) {}
}

<div class="w-full fixed top-4 z-50 max-h-32">
  <div class="px-4 navbar w-[98%] mx-auto bg-darkblue rounded-box shadow-md">
    <div class="navbar-start">
      <div class="dropdown">
        <label class="hamburger-menu btn btn-ghost btn-circle">
          <input type="checkbox"/>
        </label>
        <aside tabindex="0" class="sidebar z-[1] flex flex-col gap-2 w-full bg-contain bg-darkblue rounded-box items-start">
            <h3 class="text-2xl border-b border-[darkgrey]">Market</h3>
            <ul class='flex gap-4'>
              <li><a class="hover:border-b border-grey" routerLink="/">All</a></li>
              <!-- <li><a class="hover:border-b border-grey" routerLink="/">Selling</a></li>
              <li><a class="hover:border-b border-grey" routerLink="/">Buying</a></li>
              <li><a class="hover:border-b border-grey" routerLink="/">Trading</a></li> -->
            </ul>
        </aside>
      </div>
    </div>
    <div class="navbar-center">
      <a routerLink="/" class="btn btn-ghost font-thin normal-case lg:text-3xl">DealFortress <img src="assets/logo.png" alt="deal fortress logo" class="logo-s"/></a>
    </div>
    <div class="navbar-end">
      <div class="flex gap-4 items-center flex-1 justify-end">
        <button class="btn btn-ghost btn-circle">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>
        </button>
        <ng-container *ngIf="isAuthenticated | async">
            <app-auth-logout-button></app-auth-logout-button>
            <a class='text-3xl' to="/profile"><img [src]="(user | async)?.picture" alt="avatar" class='avatar rounded-full w-10' /></a> 
        </ng-container>
        <ng-container *ngIf="!(isAuthenticated | async)">
            <app-auth-login-button></app-auth-login-button>
        </ng-container>
      </div>
    </div>
  </div>
</div>

// frontend/src/component/Navbar.tsx
import logo from '../assets/logo.png'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faMagnifyingGlass, faHeart, faCircle } from '@fortawesome/free-solid-svg-icons'
import { Link } from 'react-router-dom'
import { useState } from 'react'
import { ProductSearch } from './Product/ProductSearch'

export const Navbar = () => {

  const [ navbarToggle, setNavbarToggle ] = useState<boolean>(false)
  const [searchFilter, setSearchFilter] = useState<string>("");

  const filterBySearch = (input : string) => {
    setSearchFilter(input);
  }


  return (
    <div className="w-screen py-4 top-0 relative bg-darkblue text-white">
        <div className='container flex justify-between items-center mx-auto gap-2'>
            <Link to="/">
                <div className='flex gap-2 items-center flex-1'>
                    <img src={logo} alt="deal fortress logo" className="logo-s "/>
                    <p>DealFortress</p>
                </div>
            </Link>
            <div className="flex gap-4 items-center flex-1 justify-end">
                <button onClick={() => setNavbarToggle(!navbarToggle)}><FontAwesomeIcon icon={faMagnifyingGlass} /></button>
                <Link to="/favourites" ><FontAwesomeIcon icon={faHeart} /></Link>
                <Link to="/profile"><FontAwesomeIcon icon={faCircle} /></Link>
            </div>
        </div>
        {
          navbarToggle && (
            <div className='flex justify-between container mx-auto gap-8'>
              <div className='flex gap-4'>
                <ul>
                  <li className='text-xl'><Link to="/">Market</Link></li>
                  <li><Link to="/">All</Link></li>
                  <li><Link to="/">Selling</Link></li>
                  <li><Link to="/">Buying</Link></li>
                  <li><Link to="/">Trading</Link></li>
                </ul>
                <ul>
                  <li className='text-xl'><Link to="/">Forum</Link></li>
                  <li><Link to="/">All</Link></li>
                </ul>
              </div>
              <ProductSearch filterBySearch={filterBySearch} />
            </div>
          )
        }
    </div>
  )
}
